CREATE OR REPLACE FILE FORMAT database.schema.txt_fixed_width TYPE
= CSV COMPRESSION
= 'AUTO' FIELD_DELIMITER
= NONE RECORD_DELIMITER
= '\n' SKIP_HEADER
= 0 TRIM_SPACE
= false ERROR_ON_COLUMN_COUNT_MISMATCH
= true NULL_IF
= ('\\n');
