CREATE OR REPLACE FILE FORMAT prod.staging.xml TYPE
= 'XML' COMPRESSION
= 'NONE' PRESERVE_SPACE
= false STRIP_OUTER_ELEMENT
= true DISABLE_SNOWFLAKE_DATA
= false DISABLE_AUTO_CONVERT
= false IGNORE_UTF8_ERRORS
= false;
