-- Make sure to specify encryption password, storage account name, and container name

CREATE MASTER KEY ENCRYPTION BY PASSOWORD  = '<strong_password>';
go
CREATE DATABASE SCOPED CREDENTIAL msi_cred WITH IDENTITY = 'Managed Service Identity';
GO

CREATE EXTERNAL DATA SOURCE [AzureDataLakeStorage] WITH (TYPE = HADOOP, LOCATION = N'abfss://<container>@<storageaccount>.dfs.core.windows.net', CREDENTIAL = [msi_cred]);
GO
CREATE EXTERNAL FILE FORMAT [CsvFileFormat] WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N',', FIRST_ROW = 1, USE_TYPE_DEFAULT = False));
GO
CREATE EXTERNAL FILE FORMAT [TsvFileFormat] WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N'\t', FIRST_ROW = 1, USE_TYPE_DEFAULT = False));
GO
CREATE EXTERNAL FILE FORMAT [PipeFileFormat] WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N'|', FIRST_ROW = 1, USE_TYPE_DEFAULT = False));
GO