---

name: Linting Checks

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.yamllint'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        # NB: --strict flag will treat warnings as errors
        run: yamllint . --strict

  python-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black --check .

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8
