---

name: Linting Checks

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.yamllint'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        # NB: --strict flag will treat warnings as errors
        run: yamllint . --strict

  squfluff-lint-bigquery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Run sqlfluff
        run: |
          sqlfluff lint --dialect bigquery BigQuery/.
          sqlfluff lint --dialect databricks Databricks/.
          sqlfluff lint --dialect redshift Redshift/.
          sqlfluff lint --dialect snowflake Snowflake/.
#          sqlfluff lint --dialect synapse Synapse/.  NB: SQLFluff does not have a Synapse Dialect implemented