---

name: Linting Checks

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.yamllint'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        # NB: --strict flag will treat warnings as errors
        run: yamllint . --strict

  squfluff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Get changed sql files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          files_yaml:  |
            sql:
              - '**.sql'

      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.sql_any_changed == 'true'
        run: |
          echo "One or more sql file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.test_all_changed_files }}"

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff>=2.2,<2.3"

      - name: Run sqlfluff
        if: steps.get_files_to_lint.outputs.lintees != ''
        shell: bash -l {0}
        run: |
         sqlfluff --version
         sqlfluff lint . 

      - name: Annotate
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"

  python-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black --check .

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8
